#!/bin/sh
# Rebuild supabase/staging/000_full_baseline.sql from every up-migration in
# supabase/migrations/ (skips *_down.sql and _TEMPLATE_*), in filename order.
# Schema only — the migrations carry no client data (065/066/072 seed prompt
# briefs, which is practice copy, not client data).
# Usage: sh scripts/staging/build-baseline.sh
set -eu
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/supabase/staging/000_full_baseline.sql"
FILES=$(ls "$ROOT"/supabase/migrations/[0-9]*.sql | grep -v '_down\.sql$')
LAST=$(basename "$(echo "$FILES" | tail -n 1)" | cut -c1-3)
{
  echo "-- ============================================================================"
  echo "-- theLeadershipWell — FULL SCHEMA BASELINE (migrations 001–$LAST, ordered)"
  echo "-- GENERATED by scripts/staging/build-baseline.sh — do not edit by hand."
  echo "-- For the STAGING Supabase project only. Contains NO client data."
  echo "-- Run order: 000_full_baseline → 003_test_email_sink → 001_synthetic_seed"
  echo "-- (the staging-db GitHub workflow does this for you)."
  echo "-- ============================================================================"
  for f in $FILES; do
    echo ""
    echo ""
    echo "-- ==================== $(basename "$f") ===================="
    cat "$f"
  done
} > "$OUT"
echo "wrote $OUT (through $LAST)"
