/**
 * Major world cities → their IANA timezone, for the timezone picker's search.
 *
 * The IANA database only carries one representative city per zone, so cities a
 * coach actually thinks of ("Mumbai", "Dubai", "Dallas") never appear. This
 * curated list makes them first-class search results — each maps to the correct
 * zone (including the half-hour/quarter-hour offsets: India +05:30, Nepal +05:45,
 * Iran +03:30, parts of Australia +09:30, Newfoundland −03:30).
 *
 * `sublabel` disambiguates same-named cities (Portland OR vs ME) and gives the
 * coach geographic context. Selecting a city stores its IANA `zone` — the city
 * name is only for finding and labeling.
 *
 * Not exhaustive, but covers the world's major metros + notable capitals. To add
 * one, append a [city, sublabel, IANA zone] row.
 */
type Row = [string, string, string]

const RAW: Row[] = [
  // ---- United States — Eastern ----
  ['New York', 'NY · USA', 'America/New_York'],
  ['NYC', 'New York · USA', 'America/New_York'],
  ['Brooklyn', 'NY · USA', 'America/New_York'],
  ['Newark', 'NJ · USA', 'America/New_York'],
  ['Boston', 'MA · USA', 'America/New_York'],
  ['Philadelphia', 'PA · USA', 'America/New_York'],
  ['Philly', 'PA · USA', 'America/New_York'],
  ['Pittsburgh', 'PA · USA', 'America/New_York'],
  ['Washington', 'DC · USA', 'America/New_York'],
  ['Washington DC', 'DC · USA', 'America/New_York'],
  ['Baltimore', 'MD · USA', 'America/New_York'],
  ['Richmond', 'VA · USA', 'America/New_York'],
  ['Virginia Beach', 'VA · USA', 'America/New_York'],
  ['Charlotte', 'NC · USA', 'America/New_York'],
  ['Raleigh', 'NC · USA', 'America/New_York'],
  ['Atlanta', 'GA · USA', 'America/New_York'],
  ['Jacksonville', 'FL · USA', 'America/New_York'],
  ['Miami', 'FL · USA', 'America/New_York'],
  ['Tampa', 'FL · USA', 'America/New_York'],
  ['Orlando', 'FL · USA', 'America/New_York'],
  ['Detroit', 'MI · USA', 'America/Detroit'],
  ['Cleveland', 'OH · USA', 'America/New_York'],
  ['Columbus', 'OH · USA', 'America/New_York'],
  ['Cincinnati', 'OH · USA', 'America/New_York'],
  ['Indianapolis', 'IN · USA', 'America/Indiana/Indianapolis'],
  ['Buffalo', 'NY · USA', 'America/New_York'],
  // ---- United States — Central ----
  ['Chicago', 'IL · USA', 'America/Chicago'],
  ['Houston', 'TX · USA', 'America/Chicago'],
  ['Dallas', 'TX · USA', 'America/Chicago'],
  ['Fort Worth', 'TX · USA', 'America/Chicago'],
  ['San Antonio', 'TX · USA', 'America/Chicago'],
  ['Austin', 'TX · USA', 'America/Chicago'],
  ['New Orleans', 'LA · USA', 'America/Chicago'],
  ['Memphis', 'TN · USA', 'America/Chicago'],
  ['Nashville', 'TN · USA', 'America/Chicago'],
  ['Oklahoma City', 'OK · USA', 'America/Chicago'],
  ['Tulsa', 'OK · USA', 'America/Chicago'],
  ['Kansas City', 'MO · USA', 'America/Chicago'],
  ['St. Louis', 'MO · USA', 'America/Chicago'],
  ['Minneapolis', 'MN · USA', 'America/Chicago'],
  ['Milwaukee', 'WI · USA', 'America/Chicago'],
  ['Madison', 'WI · USA', 'America/Chicago'],
  ['Des Moines', 'IA · USA', 'America/Chicago'],
  ['Omaha', 'NE · USA', 'America/Chicago'],
  ['Little Rock', 'AR · USA', 'America/Chicago'],
  // ---- United States — Mountain ----
  ['Denver', 'CO · USA', 'America/Denver'],
  ['Colorado Springs', 'CO · USA', 'America/Denver'],
  ['Salt Lake City', 'UT · USA', 'America/Denver'],
  ['Albuquerque', 'NM · USA', 'America/Denver'],
  ['El Paso', 'TX · USA', 'America/Denver'],
  ['Boise', 'ID · USA', 'America/Boise'],
  ['Billings', 'MT · USA', 'America/Denver'],
  ['Phoenix', 'AZ · USA (no DST)', 'America/Phoenix'],
  ['Tucson', 'AZ · USA (no DST)', 'America/Phoenix'],
  ['Mesa', 'AZ · USA (no DST)', 'America/Phoenix'],
  // ---- United States — Pacific / Alaska / Hawaii ----
  ['Los Angeles', 'CA · USA', 'America/Los_Angeles'],
  ['LA', 'California · USA', 'America/Los_Angeles'],
  ['San Diego', 'CA · USA', 'America/Los_Angeles'],
  ['San Jose', 'CA · USA', 'America/Los_Angeles'],
  ['San Francisco', 'CA · USA', 'America/Los_Angeles'],
  ['SF', 'California · USA', 'America/Los_Angeles'],
  ['Oakland', 'CA · USA', 'America/Los_Angeles'],
  ['Sacramento', 'CA · USA', 'America/Los_Angeles'],
  ['Fresno', 'CA · USA', 'America/Los_Angeles'],
  ['Long Beach', 'CA · USA', 'America/Los_Angeles'],
  ['Seattle', 'WA · USA', 'America/Los_Angeles'],
  ['Tacoma', 'WA · USA', 'America/Los_Angeles'],
  ['Spokane', 'WA · USA', 'America/Los_Angeles'],
  ['Portland', 'OR · USA', 'America/Los_Angeles'],
  ['Las Vegas', 'NV · USA', 'America/Los_Angeles'],
  ['Reno', 'NV · USA', 'America/Los_Angeles'],
  ['Anchorage', 'AK · USA', 'America/Anchorage'],
  ['Fairbanks', 'AK · USA', 'America/Anchorage'],
  ['Juneau', 'AK · USA', 'America/Juneau'],
  ['Honolulu', 'HI · USA', 'Pacific/Honolulu'],
  // ---- Canada ----
  ['Toronto', 'Canada', 'America/Toronto'],
  ['Ottawa', 'Canada', 'America/Toronto'],
  ['Montreal', 'Canada', 'America/Toronto'],
  ['Quebec City', 'Canada', 'America/Toronto'],
  ['Halifax', 'Canada', 'America/Halifax'],
  ["St. John's", 'Canada', 'America/St_Johns'],
  ['Winnipeg', 'Canada', 'America/Winnipeg'],
  ['Regina', 'Canada (no DST)', 'America/Regina'],
  ['Saskatoon', 'Canada (no DST)', 'America/Regina'],
  ['Calgary', 'Canada', 'America/Edmonton'],
  ['Edmonton', 'Canada', 'America/Edmonton'],
  ['Vancouver', 'Canada', 'America/Vancouver'],
  ['Victoria', 'Canada', 'America/Vancouver'],
  // ---- Mexico, Central America & Caribbean ----
  ['Mexico City', 'Mexico', 'America/Mexico_City'],
  ['Guadalajara', 'Mexico', 'America/Mexico_City'],
  ['Monterrey', 'Mexico', 'America/Monterrey'],
  ['Cancún', 'Mexico', 'America/Cancun'],
  ['Tijuana', 'Mexico', 'America/Tijuana'],
  ['Guatemala City', 'Guatemala', 'America/Guatemala'],
  ['San Salvador', 'El Salvador', 'America/El_Salvador'],
  ['Tegucigalpa', 'Honduras', 'America/Tegucigalpa'],
  ['Managua', 'Nicaragua', 'America/Managua'],
  ['San José', 'Costa Rica', 'America/Costa_Rica'],
  ['Panama City', 'Panama', 'America/Panama'],
  ['Havana', 'Cuba', 'America/Havana'],
  ['Santo Domingo', 'Dominican Republic', 'America/Santo_Domingo'],
  ['San Juan', 'Puerto Rico', 'America/Puerto_Rico'],
  ['Kingston', 'Jamaica', 'America/Jamaica'],
  ['Nassau', 'Bahamas', 'America/Nassau'],
  ['Port-au-Prince', 'Haiti', 'America/Port-au-Prince'],
  // ---- South America ----
  ['Bogotá', 'Colombia', 'America/Bogota'],
  ['Medellín', 'Colombia', 'America/Bogota'],
  ['Cali', 'Colombia', 'America/Bogota'],
  ['Lima', 'Peru', 'America/Lima'],
  ['Quito', 'Ecuador', 'America/Guayaquil'],
  ['Guayaquil', 'Ecuador', 'America/Guayaquil'],
  ['Caracas', 'Venezuela', 'America/Caracas'],
  ['La Paz', 'Bolivia', 'America/La_Paz'],
  ['Santiago', 'Chile', 'America/Santiago'],
  ['Buenos Aires', 'Argentina', 'America/Argentina/Buenos_Aires'],
  ['Córdoba', 'Argentina', 'America/Argentina/Cordoba'],
  ['Montevideo', 'Uruguay', 'America/Montevideo'],
  ['Asunción', 'Paraguay', 'America/Asuncion'],
  ['São Paulo', 'Brazil', 'America/Sao_Paulo'],
  ['Rio de Janeiro', 'Brazil', 'America/Sao_Paulo'],
  ['Brasília', 'Brazil', 'America/Sao_Paulo'],
  ['Belo Horizonte', 'Brazil', 'America/Sao_Paulo'],
  ['Salvador', 'Brazil', 'America/Bahia'],
  ['Fortaleza', 'Brazil', 'America/Fortaleza'],
  ['Manaus', 'Brazil', 'America/Manaus'],
  // ---- Europe — Western & Southern ----
  ['London', 'United Kingdom', 'Europe/London'],
  ['Manchester', 'United Kingdom', 'Europe/London'],
  ['Birmingham', 'United Kingdom', 'Europe/London'],
  ['Glasgow', 'United Kingdom', 'Europe/London'],
  ['Edinburgh', 'United Kingdom', 'Europe/London'],
  ['Dublin', 'Ireland', 'Europe/Dublin'],
  ['Lisbon', 'Portugal', 'Europe/Lisbon'],
  ['Porto', 'Portugal', 'Europe/Lisbon'],
  ['Madrid', 'Spain', 'Europe/Madrid'],
  ['Barcelona', 'Spain', 'Europe/Madrid'],
  ['Valencia', 'Spain', 'Europe/Madrid'],
  ['Seville', 'Spain', 'Europe/Madrid'],
  ['Paris', 'France', 'Europe/Paris'],
  ['Marseille', 'France', 'Europe/Paris'],
  ['Lyon', 'France', 'Europe/Paris'],
  ['Brussels', 'Belgium', 'Europe/Brussels'],
  ['Amsterdam', 'Netherlands', 'Europe/Amsterdam'],
  ['Rotterdam', 'Netherlands', 'Europe/Amsterdam'],
  ['Luxembourg', 'Luxembourg', 'Europe/Luxembourg'],
  ['Zurich', 'Switzerland', 'Europe/Zurich'],
  ['Geneva', 'Switzerland', 'Europe/Zurich'],
  ['Bern', 'Switzerland', 'Europe/Zurich'],
  ['Frankfurt', 'Germany', 'Europe/Berlin'],
  ['Berlin', 'Germany', 'Europe/Berlin'],
  ['Munich', 'Germany', 'Europe/Berlin'],
  ['Hamburg', 'Germany', 'Europe/Berlin'],
  ['Cologne', 'Germany', 'Europe/Berlin'],
  ['Stuttgart', 'Germany', 'Europe/Berlin'],
  ['Vienna', 'Austria', 'Europe/Vienna'],
  ['Milan', 'Italy', 'Europe/Rome'],
  ['Rome', 'Italy', 'Europe/Rome'],
  ['Naples', 'Italy', 'Europe/Rome'],
  ['Turin', 'Italy', 'Europe/Rome'],
  ['Venice', 'Italy', 'Europe/Rome'],
  ['Florence', 'Italy', 'Europe/Rome'],
  // ---- Europe — Northern, Central & Eastern ----
  ['Copenhagen', 'Denmark', 'Europe/Copenhagen'],
  ['Oslo', 'Norway', 'Europe/Oslo'],
  ['Stockholm', 'Sweden', 'Europe/Stockholm'],
  ['Gothenburg', 'Sweden', 'Europe/Stockholm'],
  ['Helsinki', 'Finland', 'Europe/Helsinki'],
  ['Reykjavik', 'Iceland', 'Atlantic/Reykjavik'],
  ['Warsaw', 'Poland', 'Europe/Warsaw'],
  ['Kraków', 'Poland', 'Europe/Warsaw'],
  ['Prague', 'Czechia', 'Europe/Prague'],
  ['Budapest', 'Hungary', 'Europe/Budapest'],
  ['Bratislava', 'Slovakia', 'Europe/Bratislava'],
  ['Ljubljana', 'Slovenia', 'Europe/Ljubljana'],
  ['Zagreb', 'Croatia', 'Europe/Zagreb'],
  ['Belgrade', 'Serbia', 'Europe/Belgrade'],
  ['Bucharest', 'Romania', 'Europe/Bucharest'],
  ['Sofia', 'Bulgaria', 'Europe/Sofia'],
  ['Athens', 'Greece', 'Europe/Athens'],
  ['Thessaloniki', 'Greece', 'Europe/Athens'],
  ['Istanbul', 'Türkiye', 'Europe/Istanbul'],
  ['Ankara', 'Türkiye', 'Europe/Istanbul'],
  ['Kyiv', 'Ukraine', 'Europe/Kyiv'],
  ['Minsk', 'Belarus', 'Europe/Minsk'],
  ['Moscow', 'Russia', 'Europe/Moscow'],
  ['St. Petersburg', 'Russia', 'Europe/Moscow'],
  ['Riga', 'Latvia', 'Europe/Riga'],
  ['Vilnius', 'Lithuania', 'Europe/Vilnius'],
  ['Tallinn', 'Estonia', 'Europe/Tallinn'],
  // ---- Middle East ----
  ['Tel Aviv', 'Israel', 'Asia/Jerusalem'],
  ['Jerusalem', 'Israel', 'Asia/Jerusalem'],
  ['Beirut', 'Lebanon', 'Asia/Beirut'],
  ['Amman', 'Jordan', 'Asia/Amman'],
  ['Damascus', 'Syria', 'Asia/Damascus'],
  ['Baghdad', 'Iraq', 'Asia/Baghdad'],
  ['Kuwait City', 'Kuwait', 'Asia/Kuwait'],
  ['Riyadh', 'Saudi Arabia', 'Asia/Riyadh'],
  ['Jeddah', 'Saudi Arabia', 'Asia/Riyadh'],
  ['Doha', 'Qatar', 'Asia/Qatar'],
  ['Manama', 'Bahrain', 'Asia/Bahrain'],
  ['Abu Dhabi', 'UAE', 'Asia/Dubai'],
  ['Dubai', 'UAE', 'Asia/Dubai'],
  ['Muscat', 'Oman', 'Asia/Muscat'],
  ['Tehran', 'Iran', 'Asia/Tehran'],
  // ---- Africa ----
  ['Cairo', 'Egypt', 'Africa/Cairo'],
  ['Alexandria', 'Egypt', 'Africa/Cairo'],
  ['Casablanca', 'Morocco', 'Africa/Casablanca'],
  ['Rabat', 'Morocco', 'Africa/Casablanca'],
  ['Algiers', 'Algeria', 'Africa/Algiers'],
  ['Tunis', 'Tunisia', 'Africa/Tunis'],
  ['Tripoli', 'Libya', 'Africa/Tripoli'],
  ['Lagos', 'Nigeria', 'Africa/Lagos'],
  ['Abuja', 'Nigeria', 'Africa/Lagos'],
  ['Accra', 'Ghana', 'Africa/Accra'],
  ['Dakar', 'Senegal', 'Africa/Dakar'],
  ['Abidjan', 'Côte d’Ivoire', 'Africa/Abidjan'],
  ['Nairobi', 'Kenya', 'Africa/Nairobi'],
  ['Addis Ababa', 'Ethiopia', 'Africa/Addis_Ababa'],
  ['Dar es Salaam', 'Tanzania', 'Africa/Dar_es_Salaam'],
  ['Kampala', 'Uganda', 'Africa/Kampala'],
  ['Kigali', 'Rwanda', 'Africa/Kigali'],
  ['Khartoum', 'Sudan', 'Africa/Khartoum'],
  ['Johannesburg', 'South Africa', 'Africa/Johannesburg'],
  ['Cape Town', 'South Africa', 'Africa/Johannesburg'],
  ['Durban', 'South Africa', 'Africa/Johannesburg'],
  ['Pretoria', 'South Africa', 'Africa/Johannesburg'],
  ['Harare', 'Zimbabwe', 'Africa/Harare'],
  ['Lusaka', 'Zambia', 'Africa/Lusaka'],
  ['Luanda', 'Angola', 'Africa/Luanda'],
  ['Kinshasa', 'DR Congo', 'Africa/Kinshasa'],
  ['Maputo', 'Mozambique', 'Africa/Maputo'],
  ['Windhoek', 'Namibia', 'Africa/Windhoek'],
  // ---- South & Central Asia ----
  ['Karachi', 'Pakistan', 'Asia/Karachi'],
  ['Lahore', 'Pakistan', 'Asia/Karachi'],
  ['Islamabad', 'Pakistan', 'Asia/Karachi'],
  ['Kabul', 'Afghanistan', 'Asia/Kabul'],
  ['Mumbai', 'India', 'Asia/Kolkata'],
  ['Delhi', 'India', 'Asia/Kolkata'],
  ['New Delhi', 'India', 'Asia/Kolkata'],
  ['Bengaluru', 'India', 'Asia/Kolkata'],
  ['Bangalore', 'India', 'Asia/Kolkata'],
  ['Hyderabad', 'India', 'Asia/Kolkata'],
  ['Chennai', 'India', 'Asia/Kolkata'],
  ['Kolkata', 'India', 'Asia/Kolkata'],
  ['Pune', 'India', 'Asia/Kolkata'],
  ['Ahmedabad', 'India', 'Asia/Kolkata'],
  ['Jaipur', 'India', 'Asia/Kolkata'],
  ['Colombo', 'Sri Lanka', 'Asia/Colombo'],
  ['Kathmandu', 'Nepal', 'Asia/Kathmandu'],
  ['Dhaka', 'Bangladesh', 'Asia/Dhaka'],
  ['Tashkent', 'Uzbekistan', 'Asia/Tashkent'],
  ['Almaty', 'Kazakhstan', 'Asia/Almaty'],
  ['Astana', 'Kazakhstan', 'Asia/Almaty'],
  // ---- East & Southeast Asia ----
  ['Bangkok', 'Thailand', 'Asia/Bangkok'],
  ['Hanoi', 'Vietnam', 'Asia/Ho_Chi_Minh'],
  ['Ho Chi Minh City', 'Vietnam', 'Asia/Ho_Chi_Minh'],
  ['Phnom Penh', 'Cambodia', 'Asia/Phnom_Penh'],
  ['Vientiane', 'Laos', 'Asia/Vientiane'],
  ['Yangon', 'Myanmar', 'Asia/Yangon'],
  ['Kuala Lumpur', 'Malaysia', 'Asia/Kuala_Lumpur'],
  ['Singapore', 'Singapore', 'Asia/Singapore'],
  ['Jakarta', 'Indonesia', 'Asia/Jakarta'],
  ['Surabaya', 'Indonesia', 'Asia/Jakarta'],
  ['Bandung', 'Indonesia', 'Asia/Jakarta'],
  ['Denpasar', 'Bali · Indonesia', 'Asia/Makassar'],
  ['Manila', 'Philippines', 'Asia/Manila'],
  ['Cebu', 'Philippines', 'Asia/Manila'],
  ['Hong Kong', 'Hong Kong', 'Asia/Hong_Kong'],
  ['Macau', 'Macau', 'Asia/Macau'],
  ['Taipei', 'Taiwan', 'Asia/Taipei'],
  ['Beijing', 'China', 'Asia/Shanghai'],
  ['Shanghai', 'China', 'Asia/Shanghai'],
  ['Guangzhou', 'China', 'Asia/Shanghai'],
  ['Shenzhen', 'China', 'Asia/Shanghai'],
  ['Chengdu', 'China', 'Asia/Shanghai'],
  ['Chongqing', 'China', 'Asia/Shanghai'],
  ['Wuhan', 'China', 'Asia/Shanghai'],
  ['Tianjin', 'China', 'Asia/Shanghai'],
  ['Seoul', 'South Korea', 'Asia/Seoul'],
  ['Busan', 'South Korea', 'Asia/Seoul'],
  ['Tokyo', 'Japan', 'Asia/Tokyo'],
  ['Osaka', 'Japan', 'Asia/Tokyo'],
  ['Yokohama', 'Japan', 'Asia/Tokyo'],
  ['Nagoya', 'Japan', 'Asia/Tokyo'],
  ['Sapporo', 'Japan', 'Asia/Tokyo'],
  ['Fukuoka', 'Japan', 'Asia/Tokyo'],
  ['Ulaanbaatar', 'Mongolia', 'Asia/Ulaanbaatar'],
  // ---- Oceania ----
  ['Sydney', 'Australia', 'Australia/Sydney'],
  ['Canberra', 'Australia', 'Australia/Sydney'],
  ['Melbourne', 'Australia', 'Australia/Melbourne'],
  ['Brisbane', 'Australia (no DST)', 'Australia/Brisbane'],
  ['Gold Coast', 'Australia (no DST)', 'Australia/Brisbane'],
  ['Adelaide', 'Australia', 'Australia/Adelaide'],
  ['Darwin', 'Australia (no DST)', 'Australia/Darwin'],
  ['Perth', 'Australia', 'Australia/Perth'],
  ['Hobart', 'Australia', 'Australia/Hobart'],
  ['Auckland', 'New Zealand', 'Pacific/Auckland'],
  ['Wellington', 'New Zealand', 'Pacific/Auckland'],
  ['Christchurch', 'New Zealand', 'Pacific/Auckland'],
  ['Suva', 'Fiji', 'Pacific/Fiji'],
  ['Port Moresby', 'Papua New Guinea', 'Pacific/Port_Moresby'],
]

export type MajorCity = { city: string; sublabel: string; zone: string }

export const MAJOR_CITIES: MajorCity[] = RAW.map(([city, sublabel, zone]) => ({ city, sublabel, zone }))
